# .github/workflows/ci.yml
name: CI – FastAPI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        # if you have extra/dev requirements:
        # pip install -r requirements-dev.txt

    - name: Run test suite
      run: |
        pytest -q

    - name: Smoke-test FastAPI startup
      run: python run.py
